[package]
name = "asn-checker-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
http-cache-reqwest = "0.16.0"
ipnet = { version = "2", features = ["serde"]  }
reqwest = "0.12.23"
reqwest-middleware = "0.4.2"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.47.1"
