[package]
name = "asnLooker-cli"
description = "Command line tool to get ASN info about IP"
version = "0.1.0"
edition = "2024"

[dependencies]
asnLookup = { path = "../../lib/asnLookup" }
clap = { version = "4.5.49", features = ["derive"] }
tokio = "1.48.0"
